### ISSUE TITLE
Does not work when root

### ISSUE THREAD

**Issue by cuzelac** [fraction/dollar-sign#1]
```
$ whoami
not-root
$ $ whoami
not-root
$ sudo su -
# whoami
root
# # whoami
#
```

**Comment by maandree** [comment]
So `#` should do the same thing except also use `sudo` if `[ ! $UID = 0 ]`.

**Comment by christianbundy** [comment]
The dollar sign still works as root, but the octothorpe is a comment character.

``` sh
$ whoami
not-root
$ $ whoami
not-root
$ sudo su -
# whoami
root
# # whoami
#
```

Can you tell me how it should work? Maybe I'm confused. Thanks!

**Comment by maandree** [comment]
How did I miss that? It is not possible to do.

**Comment by christianbundy** [comment]
It looks like you can make it work with ZSH by disabling [interactive comments](http://zsh.sourceforge.net/Intro/intro_16.html) and then setting an alias with `alias \#='$'` in your runcoms, but I think that overwriting `#` is a strange thing to do.

@cuzelac do you have any thoughts on this?
