### ISSUE TITLE
Question about the usefulness of `exec`

### ISSUE THREAD

**Issue by Potherca** [fraction/dollar-sign#2]
Just [calling the parameters](https://github.com/cowboy/dotfiles/blob/master/bin/%24) should also work:

``` bash
#!/usr/bin/env bash

"$@"
```

Is there any benefit to using `exec`?

**Comment by maandree** [comment]
Without `exec`, `sh` would still be running in the background until the command exits.
`exec` cause `sh` to only change process image (exec(3)), rather than fork and then change image.

I liked the message printed in the code you linked, although, for more, it is that I paste from my own terminal.

**Comment by Potherca** [comment]
A lot of these finer nuances are beyond my everyday grasp of how bash/shell works.

Thank you very much for explaining!

For me personally, the message would not have much benefit, as I am usually _very_ aware of what I copy/paste. Having this functionality is a great convenience, though. :smiley:
